### ISSUE TITLE
Cannot operate the tree when openNodes is set in <TreeMenu>

### ISSUE THREAD

**Issue by przeroone** [iannbing/react-simple-tree-menu#36] opened 2019-05-06 03:03 UTC
I set the tree like below

```javascript
<TreeMenu
  data={location_tree}
  onClickItem={(props) => location.href = `#/locations/${props.id}` }}
  openNodes={['location-1', 'location-1/location-2']}
>
  {({search, items}) => (
    <Fragment>
      <TextField
        label="Search a location"
        type="search"
        margin="normal"
        variant="outlined"
        fullWidth
        onChange={e => search(e.target.value)}
      />
      <List component="nav">
        {items.map(props => (
          <Item {...props} />
        ))}
      </List>
    </Fragment>
  )}
</TreeMenu>
```

Whenever the `openNodes` exists, the designated tree node can be opened successfully. However the whole tree is then not working, neither expandable nor collapsable.

Thanks!

**Comment by iannbing** [comment] 2019-05-06 10:50
It's intended behaviour. The use case of `openNodes` is to allow the parent component to control the state of `TreeMenu`. 

To give an initial state of open nodes, please use `initialOpenNodes`. Please note that currently this is only available in the beta version `react-simple-tree-menu@1.0.6-rc.2`. Later it will be released as `1.0.6`.

**Comment by iannbing** [comment] 2019-05-06 11:38
`1.0.6` has been released.

**Closed by iannbing** 2019-05-06 11:38 UTC

**Comment by przeroone** [comment] 2019-05-07 09:30
Thanks @iannbing, I will give `1.0.6` a try then.

👍

**Comment by agentS** [comment] 2019-06-21 14:54
Hey,

Unfortuantely `initialOpenNodes` is not working for me when using version 1.1.2. I am able to control the open nodes using the property `openNodes` instead of `initialOpenNodes`, but the user is not able to interact with the tree in this case. I want the user to be able to interact with the tree and to control the open/collapsed items from my code.

Below you can find the code for my tree menu component.

```jsx
class GraphPropertyView extends React.Component {
  handleClick = (key, label, ...properties) => {};

  render() {
    const { classes } = this.props;

    const properties = this.processProperties(this.props.properties, {
      index: 0,
    });
    const openNodeKeys = this.determineOpenNodes(properties, {
      currentLevel: 0,
    });
    console.log(openNodeKeys);
    return (
      <div className={classes.graphPropertyContainer}>
        <TreeMenu
          data={properties}
          initialOpenNodes={openNodeKeys}
          onClickItem={this.handleClick}
          hasSearch={false}
        />
      </div>
    );
  }

  // emulate call by reference by using a context object
  processProperties(properties, context) {
    let treeData = [];
    for (let property of properties) {
      let addedProperty = {
        key: context.index.toString(),
        label: property.name,
        nodes: []
      };
      ++context.index;
      if (typeof property === "object" && property.children) {
        addedProperty.nodes = this.processProperties(
          property.children,
          context
        );
      }
      treeData.push(addedProperty);
    }
    return treeData;
  }

  // emulate call by reference by using a context object
  determineOpenNodes(properties, context) {
    let openNodeKeys = [];
    for (let property of properties) {
      if (this.props.currentLevel > context.currentLevel) {
        openNodeKeys.push(property.key);
      }
      if ((property.nodes) && (property.nodes.length > 0)) {
        ++context.currentLevel;
        openNodeKeys.push(...this.determineOpenNodes(property.nodes, context));
        --context.currentLevel;
      }
    }
    return openNodeKeys;
  }
}
```

Btw, thank you so much for your great work!
