### ISSUE TITLE
"type": "module" in package.json causing issues (import-related)

### ISSUE THREAD

**Issue by juiceghost** [iannbing/react-simple-tree-menu#163] opened 2020-04-22 11:49 UTC
I'm not sure this isn't an error on our end, but i thought it'd be worth mentioning it here. We used react-simple-tree-menu in a Next.js project and were getting an error like this on page refresh:
Error: Must use import to load ES Module: /myProject/node_modules/react-simple-tree-menu/dist/main.cjs.js
require() of ES modules is not supported.
require() of /myProject/node_modules/react-simple-tree-menu/dist/main.cjs.js from /myProject/.next/server/static/development/pages/organisations.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename main.cjs.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /myProject/node_modules/react-simple-tree-menu/package.json.

So we went ahead and removed that line and it seems to have fixed the issue for now, seemingly without ill effects.

**Comment by iannbing** [comment] 2020-04-24 20:19
Thanks for reporting. 
However I cannot reproduce this issue. Please see [this blank nextjs project](https://github.com/iannbing/nextjs-blog).

I'll close this issue for now. If you find the root cause that should be fixed in `react-simple-tree-menu`, feel free to re-open this issue 🙂.

**Comment by pliew** [comment] 2020-06-03 21:31
We have reproduced the same issue and are using the same version of next.js and react-simple-tree-menu as your example project.

**Comment by iannbing** [comment] 2020-06-17 22:35
This has been fixed and released as v1.1.17

**Closed by iannbing** 2020-06-17 22:35 UTC
